/// Notification wording in the explanation languages (en · bn · ne · ar · id).
///
/// Placeholders: {task} {lesson} {band} {n} {skill} {name} {stage} {course}.
/// Skill, lesson and course names stay in English (as in the app).
class NotifTexts {
  NotifTexts._();

  /// Text for [key] in [lang] (English when missing), with [vars] filled in.
  static String t(String key, String lang, [Map<String, Object?> vars = const <String, Object?>{}]) {
    var s = _all[lang]?[key] ?? _all['en']![key] ?? key;
    vars.forEach((k, v) => s = s.replaceAll('{$k}', '${v ?? ''}'));
    return s;
  }

  static const Map<String, Map<String, String>> _all = <String, Map<String, String>>{
    'en': <String, String>{
      'daily_title': "Time for today's IELTS practice",
      'daily_draft': 'Your {task} draft is waiting. Finish it and get a band score.',
      'daily_lesson': 'Next up: {lesson}. It takes about 5 minutes.',
      'daily_generic': 'A 10-minute session today keeps you on track for Band {band}.',
      'daily_plan': "Today's plan: {n} tasks, about {min} minutes. First up: {task}.",
      'streak_title': 'Your {n}-day streak ends tonight',
      'streak_body': 'One short lesson keeps it alive.',
      'comeback5_title': 'We saved your place',
      'comeback5_body': 'Pick up where you left off. One lesson is enough to restart.',
      'comeback14_title': 'Still aiming for Band {band}?',
      'comeback14_body': 'Your plan is ready when you are. Start with a 5-minute lesson.',
      'weekly_title': 'Your week in review',
      'weekly_body': 'See your progress and what to practise next.',
      'task_title': 'Starting in 15 minutes: {task}',
      'task_body': 'Your planned study session is coming up.',
      'mock_title': 'Mock test day',
      'mock_body': 'Set aside about 3 hours in a quiet place. Good luck!',
      'exam_title': '{n} days to your IELTS exam',
      'exam_body': 'Keep practising a little every day.',
      'exam1_title': 'Your IELTS exam is tomorrow',
      'exam1_body': 'Rest well, and check your ID and test centre details.',
      'examday_title': 'Exam day. Good luck!',
      'examday_body': "Stay calm and read every question carefully. You've prepared for this.",
      'result_title': '{skill} scored · Band {band}',
      'result_body': 'Tap to see your feedback.',
      'best_title': 'New personal best in {skill}: Band {band}',
      'target_title': 'Target reached in {skill}: Band {band}',
      'best_body': 'Great progress. Keep it going.',
      'badge_title': 'Milestone unlocked: {name}',
      'badge_body': 'See it in your Milestones.',
      'stage_title': 'Stage complete: {stage}',
      'stage_body': '{course}: on to the next stage.',
      'quota_title': "You've reached your AI scoring limit",
      'quota_body': 'See plans to keep getting band scores.',
    },
    'bn': <String, String>{
      'daily_title': 'আজকের IELTS প্র্যাকটিসের সময়',
      'daily_draft': 'আপনার {task} ড্রাফট অপেক্ষা করছে। শেষ করে ব্যান্ড স্কোর নিন।',
      'daily_lesson': 'পরের লেসন: {lesson}। মাত্র 5 মিনিট লাগবে।',
      'daily_generic': 'আজ 10 মিনিটের একটি সেশন আপনাকে Band {band}-এর পথে রাখবে।',
      'daily_plan': 'আজকের প্ল্যান: {n}টি কাজ, প্রায় {min} মিনিট। প্রথমে: {task}।',
      'streak_title': 'আপনার {n} দিনের স্ট্রিক আজ রাতে শেষ হয়ে যাবে',
      'streak_body': 'একটি ছোট লেসন করলেই স্ট্রিক টিকে থাকবে।',
      'comeback5_title': 'আপনার জায়গা আমরা রেখে দিয়েছি',
      'comeback5_body': 'যেখানে থেমেছিলেন সেখান থেকেই শুরু করুন। একটি লেসনই যথেষ্ট।',
      'comeback14_title': 'এখনও Band {band}-এর লক্ষ্যে আছেন?',
      'comeback14_body': 'আপনার প্ল্যান তৈরি। 5 মিনিটের একটি লেসন দিয়ে শুরু করুন।',
      'weekly_title': 'আপনার সপ্তাহের সারসংক্ষেপ',
      'weekly_body': 'আপনার অগ্রগতি আর এরপর কী প্র্যাকটিস করবেন দেখুন।',
      'task_title': '15 মিনিট পরে শুরু: {task}',
      'task_body': 'আপনার পরিকল্পিত সেশনের সময় হয়ে এসেছে।',
      'mock_title': 'আজ মক টেস্টের দিন',
      'mock_body': 'শান্ত একটি জায়গায় প্রায় 3 ঘণ্টা সময় রাখুন। শুভকামনা!',
      'exam_title': 'আপনার IELTS পরীক্ষার আর {n} দিন বাকি',
      'exam_body': 'প্রতিদিন একটু করে প্র্যাকটিস চালিয়ে যান।',
      'exam1_title': 'আগামীকাল আপনার IELTS পরীক্ষা',
      'exam1_body': 'ভালোভাবে বিশ্রাম নিন, আর আইডি ও টেস্ট সেন্টারের তথ্য দেখে রাখুন।',
      'examday_title': 'আজ পরীক্ষার দিন। শুভকামনা!',
      'examday_body': 'শান্ত থাকুন, প্রতিটি প্রশ্ন মন দিয়ে পড়ুন। আপনি প্রস্তুত।',
      'result_title': '{skill} স্কোর হয়েছে · Band {band}',
      'result_body': 'ফিডব্যাক দেখতে ট্যাপ করুন।',
      'best_title': '{skill}-এ নতুন সেরা স্কোর: Band {band}',
      'target_title': '{skill}-এ লক্ষ্য পূরণ হয়েছে: Band {band}',
      'best_body': 'দারুণ অগ্রগতি। এভাবেই চালিয়ে যান।',
      'badge_title': 'নতুন মাইলস্টোন: {name}',
      'badge_body': 'আপনার Milestones-এ দেখুন।',
      'stage_title': 'স্টেজ শেষ: {stage}',
      'stage_body': '{course}: এবার পরের স্টেজ।',
      'quota_title': 'আপনার AI স্কোরিংয়ের সীমা শেষ হয়েছে',
      'quota_body': 'আরও ব্যান্ড স্কোর পেতে প্ল্যানগুলো দেখুন।',
    },
    'ne': <String, String>{
      'daily_title': 'आजको IELTS अभ्यासको समय',
      'daily_draft': 'तपाईंको {task} ड्राफ्ट पर्खिरहेको छ। पूरा गरेर ब्यान्ड स्कोर लिनुहोस्।',
      'daily_lesson': 'अर्को पाठ: {lesson}। करिब 5 मिनेट लाग्छ।',
      'daily_generic': 'आज 10 मिनेटको अभ्यासले तपाईंलाई Band {band} को बाटोमा राख्छ।',
      'daily_plan': 'आजको योजना: {n} वटा काम, करिब {min} मिनेट। पहिले: {task}।',
      'streak_title': 'तपाईंको {n} दिनको स्ट्रिक आज राति टुट्नेछ',
      'streak_body': 'एउटा छोटो पाठले स्ट्रिक जोगाउँछ।',
      'comeback5_title': 'तपाईं जहाँ रोकिनुभएको थियो, त्यो ठाउँ सुरक्षित छ',
      'comeback5_body': 'त्यहीँबाट सुरु गर्नुहोस्। फेरि सुरु गर्न एउटा पाठ नै काफी छ।',
      'comeback14_title': 'अझै Band {band} को लक्ष्यमा हुनुहुन्छ?',
      'comeback14_body': 'तपाईंको योजना तयार छ। 5 मिनेटको पाठबाट सुरु गर्नुहोस्।',
      'weekly_title': 'तपाईंको हप्ताको सारांश',
      'weekly_body': 'आफ्नो प्रगति र अब के अभ्यास गर्ने हेर्नुहोस्।',
      'task_title': '15 मिनेटमा सुरु हुँदैछ: {task}',
      'task_body': 'तपाईंले योजना गरेको अध्ययन सत्र नजिकिँदैछ।',
      'mock_title': 'आज मक टेस्टको दिन',
      'mock_body': 'शान्त ठाउँमा करिब 3 घण्टा छुट्याउनुहोस्। शुभकामना!',
      'exam_title': 'तपाईंको IELTS परीक्षामा {n} दिन बाँकी',
      'exam_body': 'हरेक दिन अलिअलि अभ्यास गरिरहनुहोस्।',
      'exam1_title': 'भोलि तपाईंको IELTS परीक्षा',
      'exam1_body': 'राम्ररी आराम गर्नुहोस्, र परिचयपत्र तथा टेस्ट सेन्टरको विवरण जाँच्नुहोस्।',
      'examday_title': 'आज परीक्षाको दिन। शुभकामना!',
      'examday_body': 'शान्त रहनुहोस् र हरेक प्रश्न ध्यान दिएर पढ्नुहोस्। तपाईं तयार हुनुहुन्छ।',
      'result_title': '{skill} स्कोर भयो · Band {band}',
      'result_body': 'आफ्नो फिडब्याक हेर्न ट्याप गर्नुहोस्।',
      'best_title': '{skill} मा नयाँ उत्कृष्ट स्कोर: Band {band}',
      'target_title': '{skill} मा लक्ष्य पूरा भयो: Band {band}',
      'best_body': 'राम्रो प्रगति। यसैगरी जारी राख्नुहोस्।',
      'badge_title': 'नयाँ माइलस्टोन: {name}',
      'badge_body': 'आफ्नो Milestones मा हेर्नुहोस्।',
      'stage_title': 'स्टेज पूरा: {stage}',
      'stage_body': '{course}: अब अर्को स्टेज।',
      'quota_title': 'तपाईंको AI स्कोरिङको सीमा पुग्यो',
      'quota_body': 'थप ब्यान्ड स्कोरका लागि योजनाहरू हेर्नुहोस्।',
    },
    'ar': <String, String>{
      'daily_title': 'حان وقت تدريب IELTS اليوم',
      'daily_draft': 'مسودة {task} بانتظارك. أكملها واحصل على درجة Band.',
      'daily_lesson': 'الدرس التالي: {lesson}. يستغرق نحو 5 دقائق.',
      'daily_generic': 'جلسة من 10 دقائق اليوم تبقيك على طريق Band {band}.',
      'daily_plan': 'خطة اليوم: {n} مهام، نحو {min} دقيقة. أولاً: {task}.',
      'streak_title': 'سلسلة أيامك المتتالية ({n}) تنتهي الليلة',
      'streak_body': 'درس قصير واحد يكفي للحفاظ عليها.',
      'comeback5_title': 'احتفظنا لك بمكانك',
      'comeback5_body': 'تابع من حيث توقفت. درس واحد يكفي للعودة.',
      'comeback14_title': 'هل ما زلت تستهدف Band {band}؟',
      'comeback14_body': 'خطتك جاهزة متى شئت. ابدأ بدرس مدته 5 دقائق.',
      'weekly_title': 'ملخص أسبوعك',
      'weekly_body': 'اطّلع على تقدمك وما تحتاج إلى التدرب عليه بعد ذلك.',
      'task_title': 'يبدأ بعد 15 دقيقة: {task}',
      'task_body': 'اقترب موعد جلستك الدراسية المخططة.',
      'mock_title': 'اليوم موعد الاختبار التجريبي',
      'mock_body': 'خصّص نحو 3 ساعات في مكان هادئ. بالتوفيق!',
      'exam_title': 'الأيام المتبقية على امتحان IELTS: {n}',
      'exam_body': 'واصل التدرب قليلًا كل يوم.',
      'exam1_title': 'امتحان IELTS غدًا',
      'exam1_body': 'خذ قسطًا كافيًا من الراحة، وتحقق من هويتك وتفاصيل مركز الامتحان.',
      'examday_title': 'اليوم يوم الامتحان. بالتوفيق!',
      'examday_body': 'حافظ على هدوئك واقرأ كل سؤال بعناية. لقد استعددت لهذا.',
      'result_title': 'تم تقييم {skill} · Band {band}',
      'result_body': 'اضغط لعرض الملاحظات.',
      'best_title': 'أفضل نتيجة جديدة في {skill}: Band {band}',
      'target_title': 'حققت هدفك في {skill}: Band {band}',
      'best_body': 'تقدم رائع. واصل على هذا النحو.',
      'badge_title': 'إنجاز جديد: {name}',
      'badge_body': 'شاهده في صفحة Milestones.',
      'stage_title': 'اكتملت المرحلة: {stage}',
      'stage_body': '{course}: انتقل إلى المرحلة التالية.',
      'quota_title': 'وصلت إلى حد التقييم بالذكاء الاصطناعي',
      'quota_body': 'اطّلع على الخطط للحصول على المزيد من درجات Band.',
    },
    'id': <String, String>{
      'daily_title': 'Waktunya latihan IELTS hari ini',
      'daily_draft': 'Draf {task} kamu menunggu. Selesaikan dan dapatkan skor band.',
      'daily_lesson': 'Berikutnya: {lesson}. Hanya sekitar 5 menit.',
      'daily_generic': 'Sesi 10 menit hari ini menjaga kamu tetap di jalur Band {band}.',
      'daily_plan': 'Rencana hari ini: {n} tugas, sekitar {min} menit. Pertama: {task}.',
      'streak_title': 'Streak {n} hari kamu berakhir malam ini',
      'streak_body': 'Satu pelajaran singkat cukup untuk menjaganya.',
      'comeback5_title': 'Posisimu sudah kami simpan',
      'comeback5_body': 'Lanjutkan dari terakhir kali. Satu pelajaran cukup untuk mulai lagi.',
      'comeback14_title': 'Masih menargetkan Band {band}?',
      'comeback14_body': 'Rencanamu sudah siap. Mulai dengan pelajaran 5 menit.',
      'weekly_title': 'Ringkasan minggumu',
      'weekly_body': 'Lihat kemajuanmu dan apa yang perlu dilatih berikutnya.',
      'task_title': 'Mulai 15 menit lagi: {task}',
      'task_body': 'Sesi belajar yang kamu rencanakan segera dimulai.',
      'mock_title': 'Hari tes simulasi',
      'mock_body': 'Sisihkan sekitar 3 jam di tempat yang tenang. Semoga sukses!',
      'exam_title': '{n} hari lagi menuju ujian IELTS',
      'exam_body': 'Terus berlatih sedikit setiap hari.',
      'exam1_title': 'Ujian IELTS kamu besok',
      'exam1_body': 'Istirahat yang cukup, lalu cek kartu identitas dan detail lokasi tes.',
      'examday_title': 'Hari ujian. Semoga sukses!',
      'examday_body': 'Tetap tenang dan baca setiap soal dengan teliti. Kamu sudah siap.',
      'result_title': '{skill} sudah dinilai · Band {band}',
      'result_body': 'Ketuk untuk melihat feedback.',
      'best_title': 'Skor terbaik baru di {skill}: Band {band}',
      'target_title': 'Target tercapai di {skill}: Band {band}',
      'best_body': 'Kemajuan hebat. Pertahankan.',
      'badge_title': 'Milestone baru: {name}',
      'badge_body': 'Lihat di Milestones kamu.',
      'stage_title': 'Tahap selesai: {stage}',
      'stage_body': '{course}: lanjut ke tahap berikutnya.',
      'quota_title': 'Batas penilaian AI kamu sudah tercapai',
      'quota_body': 'Lihat paket untuk mendapatkan lebih banyak skor band.',
    },
  };
}
